package cn.jade.rjzxjjh.mapper;

import cn.jade.rjzxjjh.model.AidedInfo;

import java.util.List;
import java.util.Map;

public interface AidedInfoMapper {


    List<AidedInfo> findList(AidedInfo aidedInfo);

    Long getCount(AidedInfo aidedInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aided_info
     *
     * @mbggenerated Fri Mar 29 14:48:40 CST 2019
     */
    int delete(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aided_info
     *
     * @mbggenerated Fri Mar 29 14:48:40 CST 2019
     */
    int insert(AidedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aided_info
     *
     * @mbggenerated Fri Mar 29 14:48:40 CST 2019
     */
    int insertSelective(AidedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aided_info
     *
     * @mbggenerated Fri Mar 29 14:48:40 CST 2019
     */
    AidedInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aided_info
     *
     * @mbggenerated Fri Mar 29 14:48:40 CST 2019
     */
    int update(AidedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aided_info
     *
     * @mbggenerated Fri Mar 29 14:48:40 CST 2019
     */
    int updateByPrimaryKey(AidedInfo record);

    List<Map<String, Object>> getMonthGroupData();
}