package cn.jade.rjzxjjh.mapper;

import cn.jade.rjzxjjh.model.Contributor;

import java.util.List;
import java.util.Map;

public interface ContributorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    int delete(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    int insert(Contributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    int insertSelective(Contributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    Contributor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    int update(Contributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contributor
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    int updateByPrimaryKey(Contributor record);

    List<Contributor> findList(Contributor contributor);

    Long getCount(Contributor contributor);

    List<Map<String, Object>> getMonthGroupData();
}