package cn.jade.rjzxjjh.mapper;

import cn.jade.rjzxjjh.model.StudentSchoolInfo;

public interface StudentSchoolInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_school_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_school_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int insert(StudentSchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_school_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int insertSelective(StudentSchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_school_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    StudentSchoolInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_school_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int updateByPrimaryKeySelective(StudentSchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_school_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int updateByPrimaryKey(StudentSchoolInfo record);

    /**
     * 根据学生ID查询最新学校信息
     * @param studentSchoolInfo
     * @return
     */
    StudentSchoolInfo selectLataest(StudentSchoolInfo studentSchoolInfo);
}