package cn.jade.rjzxjjh.mapper;

import cn.jade.rjzxjjh.model.StudentGuardian;

public interface StudentGuardianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_guardian
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_guardian
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int insert(StudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_guardian
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int insertSelective(StudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_guardian
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    StudentGuardian selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_guardian
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int updateByPrimaryKeySelective(StudentGuardian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_guardian
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int updateByPrimaryKey(StudentGuardian record);
}