package cn.jade.rjzxjjh.mapper;

import cn.jade.rjzxjjh.model.StudentBankInfo;

public interface StudentBankInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_bank_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_bank_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int insert(StudentBankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_bank_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int insertSelective(StudentBankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_bank_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    StudentBankInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_bank_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int updateByPrimaryKeySelective(StudentBankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_bank_info
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    int updateByPrimaryKey(StudentBankInfo record);
}