package cn.jade.rjzxjjh.model;

import java.util.Date;

public class ApplyFlow {

    private Page<ApplyFlow> page;

    public Page<ApplyFlow> getPage() {
        return page;
    }

    public void setPage(Page<ApplyFlow> page) {
        this.page = page;
    }

    private Student student;

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    private Integer id;
    private Integer lastStep;
    private Integer studentId;
    private Integer schoolId;
    private Date applyDate;
    private String applyAppendixId;
    private String applyRemarks;
    private String checker;
    private String checkResult;
    private Date checkSdate;
    private Date checkEdate;
    private String checkAppendixId;
    private String offlineVerifier;
    private String offlineVerifyResult;
    private String offlineVerifyAppendix;
    private Date offlineVerifySdate;
    private Date offlineVerifyEdate;
    private String approver;
    private String approveResult;
    private String approveSuggestion;
    private Date approveDate;
    private String bankName;
    private String bankUsername;
    private String bankNo;
    private String bankRemarks;
    private Double grantMoney;
    private Date grantDate;
    private String grantAccountant;
    private String grantCashier;
    private String grantRemarks;
    private String receiptAppendixId;
    private Date receiptDate;
    private String receiptRemarks;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.id
     *
     * @param id the value for apply_flow.id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.last_step
     *
     * @return the value of apply_flow.last_step
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Integer getLastStep() {
        return lastStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.last_step
     *
     * @param lastStep the value for apply_flow.last_step
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setLastStep(Integer lastStep) {
        this.lastStep = lastStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.student_id
     *
     * @return the value of apply_flow.student_id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.student_id
     *
     * @param studentId the value for apply_flow.student_id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public Integer getSchoolId() {
        return schoolId;
    }

    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.apply_date
     *
     * @return the value of apply_flow.apply_date
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.apply_date
     *
     * @param applyDate the value for apply_flow.apply_date
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.apply_appendix_id
     *
     * @return the value of apply_flow.apply_appendix_id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getApplyAppendixId() {
        return applyAppendixId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.apply_appendix_id
     *
     * @param applyAppendixId the value for apply_flow.apply_appendix_id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setApplyAppendixId(String applyAppendixId) {
        this.applyAppendixId = applyAppendixId == null ? null : applyAppendixId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.apply_remarks
     *
     * @return the value of apply_flow.apply_remarks
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getApplyRemarks() {
        return applyRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.apply_remarks
     *
     * @param applyRemarks the value for apply_flow.apply_remarks
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setApplyRemarks(String applyRemarks) {
        this.applyRemarks = applyRemarks == null ? null : applyRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.checker
     *
     * @return the value of apply_flow.checker
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.checker
     *
     * @param checker the value for apply_flow.checker
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setChecker(String checker) {
        this.checker = checker == null ? null : checker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.check_result
     *
     * @return the value of apply_flow.check_result
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.check_result
     *
     * @param checkResult the value for apply_flow.check_result
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult == null ? null : checkResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.check_sdate
     *
     * @return the value of apply_flow.check_sdate
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Date getCheckSdate() {
        return checkSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.check_sdate
     *
     * @param checkSdate the value for apply_flow.check_sdate
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setCheckSdate(Date checkSdate) {
        this.checkSdate = checkSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.check_edate
     *
     * @return the value of apply_flow.check_edate
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Date getCheckEdate() {
        return checkEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.check_edate
     *
     * @param checkEdate the value for apply_flow.check_edate
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setCheckEdate(Date checkEdate) {
        this.checkEdate = checkEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.check_appendix_id
     *
     * @return the value of apply_flow.check_appendix_id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getCheckAppendixId() {
        return checkAppendixId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.check_appendix_id
     *
     * @param checkAppendixId the value for apply_flow.check_appendix_id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setCheckAppendixId(String checkAppendixId) {
        this.checkAppendixId = checkAppendixId == null ? null : checkAppendixId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.offline_verifier
     *
     * @return the value of apply_flow.offline_verifier
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getOfflineVerifier() {
        return offlineVerifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.offline_verifier
     *
     * @param offlineVerifier the value for apply_flow.offline_verifier
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setOfflineVerifier(String offlineVerifier) {
        this.offlineVerifier = offlineVerifier == null ? null : offlineVerifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.offline_verify_result
     *
     * @return the value of apply_flow.offline_verify_result
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getOfflineVerifyResult() {
        return offlineVerifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.offline_verify_result
     *
     * @param offlineVerifyResult the value for apply_flow.offline_verify_result
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setOfflineVerifyResult(String offlineVerifyResult) {
        this.offlineVerifyResult = offlineVerifyResult == null ? null : offlineVerifyResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.offline_verify_appendix
     *
     * @return the value of apply_flow.offline_verify_appendix
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getOfflineVerifyAppendix() {
        return offlineVerifyAppendix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.offline_verify_appendix
     *
     * @param offlineVerifyAppendix the value for apply_flow.offline_verify_appendix
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setOfflineVerifyAppendix(String offlineVerifyAppendix) {
        this.offlineVerifyAppendix = offlineVerifyAppendix == null ? null : offlineVerifyAppendix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.offline_verify_sdate
     *
     * @return the value of apply_flow.offline_verify_sdate
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Date getOfflineVerifySdate() {
        return offlineVerifySdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.offline_verify_sdate
     *
     * @param offlineVerifySdate the value for apply_flow.offline_verify_sdate
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setOfflineVerifySdate(Date offlineVerifySdate) {
        this.offlineVerifySdate = offlineVerifySdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.offline_verify_edate
     *
     * @return the value of apply_flow.offline_verify_edate
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Date getOfflineVerifyEdate() {
        return offlineVerifyEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.offline_verify_edate
     *
     * @param offlineVerifyEdate the value for apply_flow.offline_verify_edate
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setOfflineVerifyEdate(Date offlineVerifyEdate) {
        this.offlineVerifyEdate = offlineVerifyEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.approver
     *
     * @return the value of apply_flow.approver
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getApprover() {
        return approver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.approver
     *
     * @param approver the value for apply_flow.approver
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setApprover(String approver) {
        this.approver = approver == null ? null : approver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.approve_result
     *
     * @return the value of apply_flow.approve_result
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getApproveResult() {
        return approveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.approve_result
     *
     * @param approveResult the value for apply_flow.approve_result
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setApproveResult(String approveResult) {
        this.approveResult = approveResult == null ? null : approveResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.approve_suggestion
     *
     * @return the value of apply_flow.approve_suggestion
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getApproveSuggestion() {
        return approveSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.approve_suggestion
     *
     * @param approveSuggestion the value for apply_flow.approve_suggestion
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setApproveSuggestion(String approveSuggestion) {
        this.approveSuggestion = approveSuggestion == null ? null : approveSuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.approve_date
     *
     * @return the value of apply_flow.approve_date
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Date getApproveDate() {
        return approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.approve_date
     *
     * @param approveDate the value for apply_flow.approve_date
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.bank_name
     *
     * @return the value of apply_flow.bank_name
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.bank_name
     *
     * @param bankName the value for apply_flow.bank_name
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.bank_username
     *
     * @return the value of apply_flow.bank_username
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getBankUsername() {
        return bankUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.bank_username
     *
     * @param bankUsername the value for apply_flow.bank_username
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setBankUsername(String bankUsername) {
        this.bankUsername = bankUsername == null ? null : bankUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.bank_no
     *
     * @return the value of apply_flow.bank_no
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.bank_no
     *
     * @param bankNo the value for apply_flow.bank_no
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.bank_remarks
     *
     * @return the value of apply_flow.bank_remarks
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getBankRemarks() {
        return bankRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.bank_remarks
     *
     * @param bankRemarks the value for apply_flow.bank_remarks
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setBankRemarks(String bankRemarks) {
        this.bankRemarks = bankRemarks == null ? null : bankRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.grant_money
     *
     * @return the value of apply_flow.grant_money
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Double getGrantMoney() {
        return grantMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.grant_money
     *
     * @param grantMoney the value for apply_flow.grant_money
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setGrantMoney(Double grantMoney) {
        this.grantMoney = grantMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.grant_date
     *
     * @return the value of apply_flow.grant_date
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Date getGrantDate() {
        return grantDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.grant_date
     *
     * @param grantDate the value for apply_flow.grant_date
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setGrantDate(Date grantDate) {
        this.grantDate = grantDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.grant_accountant
     *
     * @return the value of apply_flow.grant_accountant
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getGrantAccountant() {
        return grantAccountant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.grant_accountant
     *
     * @param grantAccountant the value for apply_flow.grant_accountant
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setGrantAccountant(String grantAccountant) {
        this.grantAccountant = grantAccountant == null ? null : grantAccountant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.grant_cashier
     *
     * @return the value of apply_flow.grant_cashier
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getGrantCashier() {
        return grantCashier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.grant_cashier
     *
     * @param grantCashier the value for apply_flow.grant_cashier
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setGrantCashier(String grantCashier) {
        this.grantCashier = grantCashier == null ? null : grantCashier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.grant_remarks
     *
     * @return the value of apply_flow.grant_remarks
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getGrantRemarks() {
        return grantRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.grant_remarks
     *
     * @param grantRemarks the value for apply_flow.grant_remarks
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setGrantRemarks(String grantRemarks) {
        this.grantRemarks = grantRemarks == null ? null : grantRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.receipt_appendix_id
     *
     * @return the value of apply_flow.receipt_appendix_id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getReceiptAppendixId() {
        return receiptAppendixId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.receipt_appendix_id
     *
     * @param receiptAppendixId the value for apply_flow.receipt_appendix_id
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setReceiptAppendixId(String receiptAppendixId) {
        this.receiptAppendixId = receiptAppendixId == null ? null : receiptAppendixId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.receipt_date
     *
     * @return the value of apply_flow.receipt_date
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public Date getReceiptDate() {
        return receiptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.receipt_date
     *
     * @param receiptDate the value for apply_flow.receipt_date
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_flow.receipt_remarks
     *
     * @return the value of apply_flow.receipt_remarks
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public String getReceiptRemarks() {
        return receiptRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_flow.receipt_remarks
     *
     * @param receiptRemarks the value for apply_flow.receipt_remarks
     *
     * @mbggenerated Tue Apr 02 21:55:05 CST 2019
     */
    public void setReceiptRemarks(String receiptRemarks) {
        this.receiptRemarks = receiptRemarks == null ? null : receiptRemarks.trim();
    }
}