package cn.jade.rjzxjjh.model;

import java.util.Date;

public class Contributor extends BasicModel<Contributor> {

    private Page<Contributor> page;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.id
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.name
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.sex
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.phone
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.weixin
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.profession
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.address
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.money
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.contributor_date
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private Date contributorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contributor.brokerage
     *
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    private String brokerage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.id
     *
     * @return the value of contributor.id
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.id
     *
     * @param id the value for contributor.id
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.name
     *
     * @return the value of contributor.name
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public String getName() {
        return name == null ? "" : name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.name
     *
     * @param name the value for contributor.name
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.sex
     *
     * @return the value of contributor.sex
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.sex
     *
     * @param sex the value for contributor.sex
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.phone
     *
     * @return the value of contributor.phone
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public String getPhone() {
        return phone == null ? "" : phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.phone
     *
     * @param phone the value for contributor.phone
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.weixin
     *
     * @return the value of contributor.weixin
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public String getWeixin() {
        return weixin == null ? "" : weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.weixin
     *
     * @param weixin the value for contributor.weixin
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.profession
     *
     * @return the value of contributor.profession
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public String getProfession() {
        return profession == null ? "" : profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.profession
     *
     * @param profession the value for contributor.profession
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.address
     *
     * @return the value of contributor.address
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public String getAddress() {
        return address == null ? "" : address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.address
     *
     * @param address the value for contributor.address
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.money
     *
     * @return the value of contributor.money
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.money
     *
     * @param money the value for contributor.money
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.contributor_date
     *
     * @return the value of contributor.contributor_date
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public Date getContributorDate() {
        return contributorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.contributor_date
     *
     * @param contributorDate the value for contributor.contributor_date
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setContributorDate(Date contributorDate) {
        this.contributorDate = contributorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contributor.brokerage
     *
     * @return the value of contributor.brokerage
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public String getBrokerage() {
        return brokerage == null ? "" : brokerage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contributor.brokerage
     *
     * @param brokerage the value for contributor.brokerage
     * @mbggenerated Thu Mar 28 18:41:39 CST 2019
     */
    public void setBrokerage(String brokerage) {
        this.brokerage = brokerage == null ? null : brokerage.trim();
    }
}