package cn.jade.rjzxjjh.model;

import cn.jade.rjzxjjh.utils.StringUtils;

public class StudentSchoolInfo extends BasicModel<StudentSchoolInfo> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer id;
    private String strId;

    public String getStrId() {
        return strId;
    }

    public void setStrId(String strId) {
        this.strId = strId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.school_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.college_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String collegeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.academic_class
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String academicClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.grade
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.class
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String schoolClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.class_teacher_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String classTeacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.class_teacher_sex
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer classTeacherSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.class_teacher_phone
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String classTeacherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.class_teacher_weixin
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String classTeacherWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_school_info.school_address
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String schoolAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.id
     *
     * @return the value of student_school_info.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.id
     *
     * @param id the value for student_school_info.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.student_id
     *
     * @return the value of student_school_info.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.student_id
     *
     * @param studentId the value for student_school_info.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.school_name
     *
     * @return the value of student_school_info.school_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.school_name
     *
     * @param schoolName the value for student_school_info.school_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.college_name
     *
     * @return the value of student_school_info.college_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.college_name
     *
     * @param collegeName the value for student_school_info.college_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.academic_class
     *
     * @return the value of student_school_info.academic_class
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getAcademicClass() {
        return academicClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.academic_class
     *
     * @param academicClass the value for student_school_info.academic_class
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setAcademicClass(String academicClass) {
        this.academicClass = academicClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.grade
     *
     * @return the value of student_school_info.grade
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.grade
     *
     * @param grade the value for student_school_info.grade
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.class
     *
     * @return the value of student_school_info.class
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getSchoolClass() {
        return schoolClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.class
     *
     * @param schoolClass the value for student_school_info.class
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setSchoolClass(String schoolClass) {
        this.schoolClass = schoolClass == null ? null : schoolClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.class_teacher_name
     *
     * @return the value of student_school_info.class_teacher_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getClassTeacherName() {
        return classTeacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.class_teacher_name
     *
     * @param classTeacherName the value for student_school_info.class_teacher_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setClassTeacherName(String classTeacherName) {
        this.classTeacherName = classTeacherName == null ? null : classTeacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.class_teacher_sex
     *
     * @return the value of student_school_info.class_teacher_sex
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getClassTeacherSex() {
        return classTeacherSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.class_teacher_sex
     *
     * @param classTeacherSex the value for student_school_info.class_teacher_sex
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setClassTeacherSex(Integer classTeacherSex) {
        this.classTeacherSex = classTeacherSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.class_teacher_phone
     *
     * @return the value of student_school_info.class_teacher_phone
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getClassTeacherPhone() {
        return classTeacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.class_teacher_phone
     *
     * @param classTeacherPhone the value for student_school_info.class_teacher_phone
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setClassTeacherPhone(String classTeacherPhone) {
        this.classTeacherPhone = classTeacherPhone == null ? null : classTeacherPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.class_teacher_weixin
     *
     * @return the value of student_school_info.class_teacher_weixin
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getClassTeacherWeixin() {
        return classTeacherWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.class_teacher_weixin
     *
     * @param classTeacherWeixin the value for student_school_info.class_teacher_weixin
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setClassTeacherWeixin(String classTeacherWeixin) {
        this.classTeacherWeixin = classTeacherWeixin == null ? null : classTeacherWeixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_school_info.school_address
     *
     * @return the value of student_school_info.school_address
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getSchoolAddress() {
        return schoolAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_school_info.school_address
     *
     * @param schoolAddress the value for student_school_info.school_address
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setSchoolAddress(String schoolAddress) {
        this.schoolAddress = schoolAddress == null ? null : schoolAddress.trim();
    }
}