package cn.jade.rjzxjjh.model;

import cn.jade.rjzxjjh.utils.StringUtils;

public class StudentBankInfo extends BasicModel<StudentBankInfo> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_bank_info.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer id;
    private String strId;

    public String getStrId() {
        return strId;
    }

    public void setStrId(String strId) {
        this.strId = strId;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_bank_info.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_bank_info.bank_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_bank_info.bank_user_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String bankUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_bank_info.bank_card_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String bankCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_bank_info.description
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_bank_info.id
     *
     * @return the value of student_bank_info.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_bank_info.id
     *
     * @param id the value for student_bank_info.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_bank_info.student_id
     *
     * @return the value of student_bank_info.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_bank_info.student_id
     *
     * @param studentId the value for student_bank_info.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_bank_info.bank_name
     *
     * @return the value of student_bank_info.bank_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_bank_info.bank_name
     *
     * @param bankName the value for student_bank_info.bank_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_bank_info.bank_user_name
     *
     * @return the value of student_bank_info.bank_user_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getBankUserName() {
        return bankUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_bank_info.bank_user_name
     *
     * @param bankUserName the value for student_bank_info.bank_user_name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setBankUserName(String bankUserName) {
        this.bankUserName = bankUserName == null ? null : bankUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_bank_info.bank_card_id
     *
     * @return the value of student_bank_info.bank_card_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getBankCardId() {
        return bankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_bank_info.bank_card_id
     *
     * @param bankCardId the value for student_bank_info.bank_card_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setBankCardId(String bankCardId) {
        this.bankCardId = bankCardId == null ? null : bankCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_bank_info.description
     *
     * @return the value of student_bank_info.description
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_bank_info.description
     *
     * @param description the value for student_bank_info.description
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}