package cn.jade.rjzxjjh.model;

public class StudentGuardian extends BasicModel<StudentGuardian> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.relation
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.age
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.id_card_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String idCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.phone_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.weixin_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String weixinNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.qq_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String qqNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.email
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.workspace
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String workspace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_guardian.relat_address
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    private String relatAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.id
     *
     * @return the value of student_guardian.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.id
     *
     * @param id the value for student_guardian.id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.name
     *
     * @return the value of student_guardian.name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.name
     *
     * @param name the value for student_guardian.name
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.relation
     *
     * @return the value of student_guardian.relation
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.relation
     *
     * @param relation the value for student_guardian.relation
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.student_id
     *
     * @return the value of student_guardian.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.student_id
     *
     * @param studentId the value for student_guardian.student_id
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.age
     *
     * @return the value of student_guardian.age
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.age
     *
     * @param age the value for student_guardian.age
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.id_card_number
     *
     * @return the value of student_guardian.id_card_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.id_card_number
     *
     * @param idCardNumber the value for student_guardian.id_card_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setIdCardNumber(String idCardNumber) {
        this.idCardNumber = idCardNumber == null ? null : idCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.phone_number
     *
     * @return the value of student_guardian.phone_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.phone_number
     *
     * @param phoneNumber the value for student_guardian.phone_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.weixin_number
     *
     * @return the value of student_guardian.weixin_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getWeixinNumber() {
        return weixinNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.weixin_number
     *
     * @param weixinNumber the value for student_guardian.weixin_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setWeixinNumber(String weixinNumber) {
        this.weixinNumber = weixinNumber == null ? null : weixinNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.qq_number
     *
     * @return the value of student_guardian.qq_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getQqNumber() {
        return qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.qq_number
     *
     * @param qqNumber the value for student_guardian.qq_number
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setQqNumber(String qqNumber) {
        this.qqNumber = qqNumber == null ? null : qqNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.email
     *
     * @return the value of student_guardian.email
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.email
     *
     * @param email the value for student_guardian.email
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.workspace
     *
     * @return the value of student_guardian.workspace
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getWorkspace() {
        return workspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.workspace
     *
     * @param workspace the value for student_guardian.workspace
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setWorkspace(String workspace) {
        this.workspace = workspace == null ? null : workspace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_guardian.relat_address
     *
     * @return the value of student_guardian.relat_address
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public String getRelatAddress() {
        return relatAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_guardian.relat_address
     *
     * @param relatAddress the value for student_guardian.relat_address
     *
     * @mbggenerated Mon Mar 04 11:56:36 CST 2019
     */
    public void setRelatAddress(String relatAddress) {
        this.relatAddress = relatAddress == null ? null : relatAddress.trim();
    }
}